version: 2.1

executors:
  node-executor:
    docker:
      - image: node:lts-alpine3.19

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd blogs-backend && npm install

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Change to Backend Directory
          command: cd blogs-backend
      - run:
          name: Grant Execute Permission to Jest
          command: chmod +x /node_modules/.bin/jest
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
