version: 2.1

executors:
  node-executor:
    docker:
      - image: node:lts-alpine3.19 # the primary container, where your job's commands are run

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      run: npm install # install dependencies
      - run:
          name: Install Dependencies
          command: cd Blog-Backend && npm run build

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: cd Blog-Backend && npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
