version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20.15.0

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
